### ISSUE TITLE
New plugin with similar featureset

### ISSUE THREAD

**Issue by svetogam** [KoBeWi/Godot-Auto-Export-Version#12]
I couldn't find a better way to let you know about this. I made a new plugin modified from this one with a similar but different set of features: https://codeberg.org/svetogam/yourbuil

It can be cleaner to use that plugin to save build data and then have a simpler version of this plugin to update the version in project settings according to it. That's especially true if you want to use the build data outside of modifying the project settings.

I'm going to release it on the asset library soon so let me know if there's something you would like me to change in regard to crediting this one. Thanks, and feel free to close this issue without a reply.

**Comment by KoBeWi** [comment]
> I couldn't find a better way to let you know about this.

You can contact me on Godot's [developer chat](https://chat.godotengine.org/) (or Discord).
